name: smart_home
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0 # Updated to latest version if available
  http: ^1.2.2
  charts_flutter: ^0.12.0
  sensors_plus: ^6.0.0
  fl_chart: ^0.36.0
  geolocator: ^9.0.2
  light: ^3.0.1
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
